# Generated by Django 5.0.1 on 2024-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuarios', models.TextField(max_length=50)),
                ('correoUsuarios', models.EmailField(max_length=254)),
                ('passwordUsuarios', models.TextField(max_length=10)),
            ],
        ),
    ]
